name: hello-python
version: 1.0
author: toby
description: a python plugin example.
enabled: true

command-group:
  name: hello
  description: comment to descripe hello command group.
  commands:
    - name: python
      type: python
      description: this is a hello from python plugin
      invoke: hello.py
