name: hello-cmd
version: 1.0
author: toby
description: a cmd plugin example.
enabled: true

command-group:
  name: hello
  description: comment to descripe hello command group.
  commands:
    - name: cmd
      type: shell
      description: this is a hello from batch command plugin
      invoke: hello.cmd
